name: dib_stable
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - anyio=4.12.1
  - async-timeout=5.0.1
  - attrs=25.4.0
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cpython=3.10.19
  - datasets=4.5.0
  - dill=0.4.0
  - exceptiongroup=1.3.1
  - filelock=3.20.3
  - frozenlist=1.7.0
  - fsspec=2025.10.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - h2=4.3.0
  - hf-xet=1.2.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=1.4.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - jinja2=3.1.6
  - joblib=1.5.3
  - krb5=1.21.3
  - lcms2=2.18
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=23.0.0
  - libarrow-acero=23.0.0
  - libarrow-compute=23.0.0
  - libarrow-dataset=23.0.0
  - libarrow-substrait=23.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=23.0.0
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libthrift=0.22.0
  - libtiff=4.7.1
  - libutf8proc=2.11.3
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.7.0
  - multiprocess=0.70.18
  - ncurses=6.5
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - numpy=2.2.6
  - openjpeg=2.5.4
  - openssl=3.6.1
  - orc=2.2.2
  - packaging=26.0
  - pandas=2.3.3
  - pillow=12.1.0
  - pip=26.0
  - prometheus-cpp=1.3.0
  - propcache=0.3.1
  - pthread-stubs=0.4
  - pyarrow=23.0.0
  - pyarrow-core=23.0.0
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.19
  - python-tzdata=2025.3
  - python-xxhash=3.6.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - re2=2025.11.05
  - readline=8.3
  - regex=2026.1.15
  - requests=2.32.5
  - safetensors=0.7.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - setuptools=80.10.2
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tokenizers=0.22.2
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm=4.67.3
  - transformers=5.0.0
  - typer-slim=0.21.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wheel=0.46.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - psutil==7.2.2
      - sentencepiece==0.2.1
      - sympy==1.13.1
prefix: /opt/miniconda3/envs/dib_stable
